Repository bekri78/teamWorflow, pull requests merged in 2022-01, with the labels that each got.

#1 feat:modification du header background en rouge
  src/App.css
  src/App.js
Labels: feat

#2 fix(logo): delete react logo to macaron logo
  src/App.js
  src/macaron.png
Labels: bug

#3 ficed logo
  src/App.js
  src/macaron.png
Labels: bug

#4 Release/0.1
  src/App.css
  src/App.js
Labels: review

#6 hotfix(hotfix2): hotfixe camelcase
  src/App.js
Labels: bug

#8 Hotfix/hotfix2
  src/App.js
Labels: bug
